name: Generate VerifyML Report

on:
  pull_request:
    branches:
      - "*"

jobs:
  report-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Current Branch
        uses: actions/checkout@v2

      - name: Generate VerifyML Report
        uses: cylynx/verifyml-reports@v1
        with:
          data-path: "/examples/model_card_output/data/breast_cancer_diagnostic_model_card.proto"
